In [1]:
import xarray as xr
import numpy as np
import metpy.calc as mpcalc
from metpy.units import units

In [2]:
files = ['cm1out_000005.nc','cm1out_000006.nc',
        'cm1out_000007.nc','cm1out_000008.nc']

In [3]:
ds = xr.open_mfdataset(files)

In [4]:
dx = ds['xh'].isel(time=0)*units('m')
dy = ds['yh'].isel(time=0)*units('m')
dz = ds['zh'].isel(time=0)*units('m')

In [5]:
wspd = mpcalc.wind_speed(ds['u'].isel(nk=0), ds['v'].isel(nk=0))

In [6]:
np.where(wspd>=100*units('m/s'))

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
 array([ 459,  459,  460,  480,  480,  480,  481,  481,  481,  492,  492,
         492,  493,  493,  493,  494,  494,  565,  565,  566,  566,  567,
         738,  758,  759,  760,  842, 1006, 1007,  461,  480,  480,  481,
         494,  494,  494,  495,  495,  495,  495,  568,  568,  569,  569,
         736,  760,  761,  762,  844,  845, 1008, 1009,  462,  463,  480,
         480,  480,  496,  496,  496,  497,  497,  497,  570,  570,  571,
         571,  733,  734,  735, 1010,  464,  465,  480,  480,  498,  498,
         498,  499,  499,  572,  573,  731,  732, 1012]),
 array([ 996,  997,  997,  691,  692,  693,  691,  692,  693, 1004, 1005,
        1006, 1004, 1005, 1006, 1004, 1005, 1044, 1045, 1045,

In [7]:
by_time = []
for i in range(0, 4):
    wspd = mpcalc.wind_speed(ds['u'].isel(nk=0, time=i), ds['v'].isel(nk=0, time=i))
    loc = np.where(wspd>=100*units('m/s'))
    by_time.append(loc)

In [8]:
by_time

[(array([ 459,  459,  460,  480,  480,  480,  481,  481,  481,  492,  492,
          492,  493,  493,  493,  494,  494,  565,  565,  566,  566,  567,
          738,  758,  759,  760,  842, 1006, 1007]),
  array([ 996,  997,  997,  691,  692,  693,  691,  692,  693, 1004, 1005,
         1006, 1004, 1005, 1006, 1004, 1005, 1044, 1045, 1045, 1046, 1046,
          418, 1229, 1229, 1229, 1207, 1163, 1163])),
 (array([ 461,  480,  480,  481,  494,  494,  494,  495,  495,  495,  495,
          568,  568,  569,  569,  736,  760,  761,  762,  844,  845, 1008,
         1009]),
  array([ 999,  694,  695,  695, 1006, 1007, 1008, 1005, 1006, 1007, 1008,
         1046, 1047, 1047, 1048,  419, 1228, 1228, 1228, 1206, 1206, 1161,
         1161])),
 (array([ 462,  463,  480,  480,  480,  496,  496,  496,  497,  497,  497,
          570,  570,  571,  571,  733,  734,  735, 1010]),
  array([1001, 1001,  696,  697,  698, 1008, 1009, 1010, 1008, 1009, 1010,
         1047, 1048, 1048, 1049,  420,  420,  420

In [9]:
time1_locs = by_time[0]
time2_locs = by_time[1]
time3_locs = by_time[2]
time4_locs = by_time[3]

In [10]:
time1_locs

(array([ 459,  459,  460,  480,  480,  480,  481,  481,  481,  492,  492,
         492,  493,  493,  493,  494,  494,  565,  565,  566,  566,  567,
         738,  758,  759,  760,  842, 1006, 1007]),
 array([ 996,  997,  997,  691,  692,  693,  691,  692,  693, 1004, 1005,
        1006, 1004, 1005, 1006, 1004, 1005, 1044, 1045, 1045, 1046, 1046,
         418, 1229, 1229, 1229, 1207, 1163, 1163]))

## ok, let's try something else ##

In [11]:
ds=xr.open_dataset('cm1out_000005.nc')

num_x = ds.ni
num_y = ds.nj
num_z = ds.nk

dx = ds['xh']*units('m')
dy = ds['yh']*units('m')
dz = ds['zh']*units('m')

u = ds['u']
v = ds['v']
w = ds['w']

x_space = 31.25*units('m')
y_space = 31.25*units('m')
z_space = 15.625*units('m')

In [12]:
wspd = mpcalc.wind_speed(ds['u'].isel(nk=0), ds['v'].isel(nk=0))
rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])

/tmp/ipykernel_3708683/946820300.py:2: UserWarning: Horizontal dimension numbers not found. Defaulting to (..., Y, X) order.
  rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])


In [13]:
condition = np.logical_and(wspd>=100*units('m/s'), rel_vort>=.2*units('1/s'))

In [14]:
np.where(condition==True) #t, y, x order

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([459, 459, 460, 481, 481, 481, 493, 493, 494, 494]),
 array([ 996,  997,  997,  691,  692,  693, 1004, 1005, 1004, 1005]))

 these are lowest model level conditions...could broaden to Wu et al. (2018, 2019): rel vort not less than .2 in lowest 3000 m, w over 20 m/s in lowest 3000 m, doesnt use wspd threshold, circulation has to have diameter of 1-2 km (but not gonna worry about that yet)

# let's see what chatgpt has to say

In [19]:
condition_wspd = wspd >= 100*units('m/s')
condition_vort = rel_vort >= .2*units('1/s')

In [23]:
window_size = 4 # 3 data points plus the current one
no_spatial_overlap_wspd = (condition_wspd.rolling(ni=window_size, min_periods=1).sum() == 1) & (condition_wspd.rolling(nj=window_size, min_periods=1).sum() == 1)
no_spatial_overlap_vort = (condition_vort.rolling(ni=window_size, min_periods=1).sum() == 1) & (condition_vort.rolling(nj=window_size, min_periods=1).sum() == 1)

In [24]:
apply_conditions = no_spatial_overlap_wspd & condition_wspd & no_spatial_overlap_vort & condition_vort

# well that was wrong...instead of selecting only one of the indices within 3 data points of each other, i eliminated them all

In [61]:
condition_wspd = wspd >= 100*units('m/s')
condition_vort = rel_vort >= .2*units('1/s')

combined_condition = condition_wspd & condition_vort

initial_indices = np.argwhere((condition_wspd & condition_vort).values)

# function to filter indices that are not within 3 indices of each other in both "ni" and "nj" dimensions
def filter_indices(indices):
    selected_indices = []
    for index in indices:
        if not any(np.all(np.abs(index - other) <= 3) for other in selected_indices):
            selected_indices.append(index)
    return selected_indices

# filter the initial indices
final_indices = filter_indices(initial_indices)

In [71]:
final_indices

[array([  0, 459, 996]), array([  0, 481, 691]), array([   0,  493, 1004])]

# okay...apply to multitple times

In [80]:
ds = xr.open_dataset('cm1out_000006.nc')

dx = ds['xh']*units('m')
dy = ds['yh']*units('m')
dz = ds['zh']*units('m')

wspd = mpcalc.wind_speed(ds['u'].isel(nk=0), ds['v'].isel(nk=0))
rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])

condition_wspd = wspd >= 100*units('m/s')
condition_vort = rel_vort >= .2*units('1/s')

combined_condition = condition_wspd & condition_vort

initial_indices = np.argwhere((condition_wspd & condition_vort).values)

# function to filter indices that are not within 3 indices of each other in both "ni" and "nj" dimensions
def filter_indices(indices):
    selected_indices = []
    for index in indices:
        if not any(np.all(np.abs(index - other) <= 3) for other in selected_indices):
            selected_indices.append(index)
    return selected_indices

# filter the initial indices
final_indices = filter_indices(initial_indices)
final_indices

/tmp/ipykernel_3708683/3290436273.py:8: UserWarning: Horizontal dimension numbers not found. Defaulting to (..., Y, X) order.
  rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])


[array([  0, 461, 999]),
 array([  0, 480, 694]),
 array([   0,  495, 1005]),
 array([   0,  762, 1228])]

In [81]:
ds = xr.open_dataset('cm1out_000007.nc')

dx = ds['xh']*units('m')
dy = ds['yh']*units('m')
dz = ds['zh']*units('m')

wspd = mpcalc.wind_speed(ds['u'].isel(nk=0), ds['v'].isel(nk=0))
rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])

condition_wspd = wspd >= 100*units('m/s')
condition_vort = rel_vort >= .2*units('1/s')

combined_condition = condition_wspd & condition_vort

initial_indices = np.argwhere((condition_wspd & condition_vort).values)

# function to filter indices that are not within 3 indices of each other in both "ni" and "nj" dimensions
def filter_indices(indices):
    selected_indices = []
    for index in indices:
        if not any(np.all(np.abs(index - other) <= 3) for other in selected_indices):
            selected_indices.append(index)
    return selected_indices

# filter the initial indices
final_indices = filter_indices(initial_indices)
final_indices

/tmp/ipykernel_3708683/3595271176.py:8: UserWarning: Horizontal dimension numbers not found. Defaulting to (..., Y, X) order.
  rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])


[array([   0,  463, 1001]),
 array([  0, 480, 696]),
 array([   0,  497, 1008]),
 array([   0,  570, 1047]),
 array([  0, 733, 420]),
 array([   0, 1010, 1159])]

In [82]:
ds = xr.open_dataset('cm1out_000008.nc')

dx = ds['xh']*units('m')
dy = ds['yh']*units('m')
dz = ds['zh']*units('m')

wspd = mpcalc.wind_speed(ds['u'].isel(nk=0), ds['v'].isel(nk=0))
rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])

condition_wspd = wspd >= 100*units('m/s')
condition_vort = rel_vort >= .2*units('1/s')

combined_condition = condition_wspd & condition_vort

initial_indices = np.argwhere((condition_wspd & condition_vort).values)

# function to filter indices that are not within 3 indices of each other in both "ni" and "nj" dimensions
def filter_indices(indices):
    selected_indices = []
    for index in indices:
        if not any(np.all(np.abs(index - other) <= 3) for other in selected_indices):
            selected_indices.append(index)
    return selected_indices

# filter the initial indices
final_indices = filter_indices(initial_indices)
final_indices

/tmp/ipykernel_3708683/247533993.py:8: UserWarning: Horizontal dimension numbers not found. Defaulting to (..., Y, X) order.
  rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])


[array([   0,  464, 1003]),
 array([  0, 480, 699]),
 array([   0,  498, 1009]),
 array([  0, 731, 421]),
 array([   0, 1012, 1157])]

In [83]:
ds = xr.open_dataset('cm1out_000009.nc')

dx = ds['xh']*units('m')
dy = ds['yh']*units('m')
dz = ds['zh']*units('m')

wspd = mpcalc.wind_speed(ds['u'].isel(nk=0), ds['v'].isel(nk=0))
rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])

condition_wspd = wspd >= 100*units('m/s')
condition_vort = rel_vort >= .2*units('1/s')

combined_condition = condition_wspd & condition_vort

initial_indices = np.argwhere((condition_wspd & condition_vort).values)

# function to filter indices that are not within 3 indices of each other in both "ni" and "nj" dimensions
def filter_indices(indices):
    selected_indices = []
    for index in indices:
        if not any(np.all(np.abs(index - other) <= 3) for other in selected_indices):
            selected_indices.append(index)
    return selected_indices

# filter the initial indices
final_indices = filter_indices(initial_indices)
final_indices

/tmp/ipykernel_3708683/2192156186.py:8: UserWarning: Horizontal dimension numbers not found. Defaulting to (..., Y, X) order.
  rel_vort = mpcalc.vorticity(ds['u'].isel(nk=0), ds['v'].isel(nk=0), dx=dx[1]-dx[0], dy=dy[1]-dy[0])


[array([   0,  466, 1005]),
 array([  0, 479, 702]),
 array([   0,  500, 1012]),
 array([   0, 1014, 1155])]

# cool...but for some reason it takes 8 million years to calculate vorticity for multiple times at once using mfdataset...enough that i have to stop the cell from running...and this method still isnt useful for the entire dataset without dask